### ISSUE TITLE
Bug on Spigot 1.16.5

### ISSUE THREAD

**Issue by morgan2233** [LielAmar/2FA#31]
Using on Spigot 1.16.5 (470) and Bungee (using MYSQL). Happenses when I do /2fa setup

```
[05:02:03] [Craft Scheduler Thread - 7/WARN]: [2FA] Plugin 2FA v1.1.8 generated an exception while executing task 108920
java.lang.NoClassDefFoundError: Could not initialize class java.awt.GraphicsEnvironment$LocalGE
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129) ~[?:?]
	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181) ~[?:?]
	at com.lielamar.auth.bukkit.utils.ImageRender.resize(ImageRender.java:56) ~[?:?]
	at com.lielamar.auth.bukkit.utils.ImageRender.getImage(ImageRender.java:48) ~[?:?]
	at com.lielamar.auth.bukkit.utils.ImageRender.<init>(ImageRender.java:28) ~[?:?]
	at com.lielamar.auth.bukkit.handlers.AuthHandler$1.run(AuthHandler.java:286) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-470]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-470]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-470]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by LielAmar** [comment]
I believe we already discussed this issue on discord.
The issue is with a library missing from the installed JRE.
