### ISSUE TITLE
Plugin 2FA v1.2.4 generated an exception while executing task 15

### ISSUE THREAD

**Issue by iGabyTM** [LielAmar/2FA#33]
This warning came out of nowhere after updating to v1.2.4
```sql
[01:18:56 WARN]: [2FA] Plugin 2FA v1.2.4 generated an exception while executing task 15
java.util.ConcurrentModificationException: null
        at java.util.HashMap.forEach(HashMap.java:1428) ~[?:?]
        at com.lielamar.auth.bukkit.handlers.BungeecordMessageHandler.lambda$new$1(BungeecordMessageHandler.java:35) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]```

**Comment by LielAmar** [comment]
Should be fixed now! :)
