### ISSUE TITLE
Data truncation: Data too long for column 'ip' at row 1

### ISSUE THREAD

**Issue by dm1lk** [LielAmar/2FA#42]
This error occurs when entering your two-factor code, the IP data fails to save to the database making the plugin require authentication each time you log in.

```
[21:42:18] [Server thread/INFO]: dm1lk issued server command: /2fa 014479
[21:42:18] [Server thread/WARN]: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'ip' at row 1
[21:42:18] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
[21:42:18] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[21:42:18] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
[21:42:18] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
[21:42:18] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
[21:42:18] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
[21:42:18] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[21:42:18] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[21:42:18] [Server thread/WARN]: 	at com.lielamar.auth.shared.storage.sql.SQLStorage.setIP(SQLStorage.java:211)
[21:42:18] [Server thread/WARN]: 	at com.lielamar.auth.bukkit.handlers.AuthHandler.updatePlayerIP(AuthHandler.java:257)
[21:42:18] [Server thread/WARN]: 	at com.lielamar.auth.bukkit.handlers.AuthHandler.approveKey(AuthHandler.java:101)
[21:42:18] [Server thread/WARN]: 	at com.lielamar.auth.bukkit.commands.subcommands.SetupCommand.execute(SetupCommand.java:56)
[21:42:18] [Server thread/WARN]: 	at com.lielamar.auth.bukkit.commands.CommandHandler.onCommand(CommandHandler.java:107)
[21:42:18] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[21:42:18] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[21:42:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[21:42:18] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2301)
[21:42:18] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2112)
[21:42:18] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2093)
[21:42:18] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[21:42:18] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[21:42:18] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[21:42:18] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[21:42:18] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[21:42:18] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[21:42:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1422)
[21:42:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[21:42:18] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[21:42:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1400)
[21:42:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1393)
[21:42:18] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[21:42:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1369)
[21:42:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1280)
[21:42:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[21:42:18] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

```

**Comment by LielAmar** [comment]
Hi milk,
I'm going to need you to send me a picture of the table created in your database.
I need to see the settings, types of each column and the length of each one as well.

**Comment by LielAmar** [comment]
The next version will support 256 characters when hashing.
This problem only occurs with SHA-512, you can use SHA-256 until the next version releases.
