### ISSUE TITLE
Cant use

### ISSUE THREAD

**Issue by SouthTownt** [LielAmar/2FA#45]
I can connect www.google.com but i cant use 2fa can u help me? thanks

Server Java and OS:

16.0.1+9-24Windows Server 2019

Server Plugins:

CoreProtect - 20.0 + [Intelli] | Enabled: true
LuckPerms - 5.3.53 + [Luck] | Enabled: true
momojs - 1.0.0 + [kouyoux] | Enabled: true
Adyeshach - 1.2.23 + [Bkm016, Arasple, Soldier233] | Enabled: true
2FA - 1.4.1 + [LielAmar] | Enabled: true
CheatCommand - 1.0.0 + [Ray_Hughes] | Enabled: true
PlaceholderAPI - 2.10.10 + [HelpChat] | Enabled: true
TAB-BukkitBridge - 1.5.1 + [NEZNAMY] | Enabled: true
Vault - 1.7.3-b${env.TRAVIS_BUILD_NUMBER} + [cereal, Sleaker, mung3r] | Enabled: true
ProtocolLib - 4.7.0 + [dmulloy2, comphenix] | Enabled: true
TrMenu - 3.0-PRE-9 + [Arasple] | Enabled: true
AdvancedColorAPI - 0.1 + [NitkaNikita] | Enabled: true
DogHook - 1.1-SNAPSHOT + [wangcai] | Enabled: true
TrChat - 1.72 + [Arasple] | Enabled: true
CMILib - 1.0.2.14 + [Zrips] | Enabled: true
CMI - 8.8.5.0 + [Zrips] | Enabled: true

Server Jar & Version:
git-Paper-783 (MC: 1.16.5)
1.16.5-R0.1-SNAPSHOT
v1_16_R3

Using bungeecord: false
Loaded bungeecord: false

Send this on Github Issue Tracker: https://github.com/LielAmar/2FA/issues
Or create a Ticket in the discord server: https://discord.com/invite/NzgBrqR

**Comment by LielAmar** [comment]
Hi!
I will need further explanation.

What exactly happens?

**Comment by SouthTownt** [comment]
My English is bad sry
when i join my server, i cant see the QRCODE( first install this plugin and i use /2fa reset after that)
it noticed "invalid url"

**Comment by LielAmar** [comment]
Can you take some screenshots, or even better - a video, and attach it here?
Also, do you have any errors in the console?

**Comment by SouthTownt** [comment]
sry when i back home i will try again
but i have the warn
[14:18:21] [Craft Scheduler Thread - 33/WARN]: java.net.ConnectException: Connection timed out: connect
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/sun.nio.ch.Net.connect0(Native Method)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/sun.nio.ch.Net.connect(Net.java:576)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/sun.nio.ch.Net.connect(Net.java:565)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/java.net.Socket.connect(Socket.java:645)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:290)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:497)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:600)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:379)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1120)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1653)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/java.net.URL.openStream(URL.java:1192)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at com.lielamar.auth.bukkit.utils.ImageRender.resize(ImageRender.java:54)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at com.lielamar.auth.bukkit.utils.ImageRender.getImage(ImageRender.java:48)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at com.lielamar.auth.bukkit.utils.ImageRender.<init>(ImageRender.java:28)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at com.lielamar.auth.bukkit.handlers.AuthHandler$2.run(AuthHandler.java:294)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[14:18:21] [Craft Scheduler Thread - 33/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

and i can use google..?

**Comment by LielAmar** [comment]
This is still not enough information, I'm going to need to know exactly what's happening in order to find a solution.

**Comment by SouthTownt** [comment]
https://cowtransfer.com/s/c3d052793eb346
this is my log
can u download it?

as a pic, i use /2fa and there isn't a QRCODE.

**Comment by LielAmar** [comment]
Seeks like the problem is in the creation of the QR Code.
This seems like a problem on your end. Make sure your server is able to connect to the Google service for creating QR codes.

**Comment by LielAmar** [comment]
Can't find any reason for this bug.
Closed.
