### ISSUE TITLE
Can't use MariaDB

### ISSUE THREAD

**Issue by GovindasOM** [LielAmar/2FA#46]
Error:
```
```
[06:44:58 WARN]: java.lang.RuntimeException: java.lang.NoSuchMethodException: org.mariadb.jdbc.MariaDbDataSource.<init>()
[06:44:58 WARN]:        at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:107)
[06:44:58 WARN]:        at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:327)
[06:44:58 WARN]:        at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114)
[06:44:58 WARN]:        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108)
[06:44:58 WARN]:        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
[06:44:58 WARN]:        at com.lielamar.auth.shared.storage.sql.SQLStorage.createTables(SQLStorage.java:84)
[06:44:58 WARN]:        at com.lielamar.auth.shared.storage.sql.SQLStorage.setupHikari(SQLStorage.java:74)
[06:44:58 WARN]:        at com.lielamar.auth.shared.storage.sql.SQLStorage.<init>(SQLStorage.java:48)
[06:44:58 WARN]:        at com.lielamar.auth.shared.storage.StorageHandler.loadStorageHandler(StorageHandler.java:93)
[06:44:58 WARN]:        at com.lielamar.auth.bukkit.TwoFactorAuthentication.setupAuth(TwoFactorAuthentication.java:64)
[06:44:58 WARN]:        at com.lielamar.auth.bukkit.commands.subcommands.ReloadCommand.execute(ReloadCommand.java:55)
[06:44:58 WARN]:        at com.lielamar.auth.bukkit.commands.CommandHandler.onCommand(CommandHandler.java:122)
[06:44:58 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[06:44:58 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[06:44:58 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[06:44:58 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:788)
[06:44:58 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:483)
[06:44:58 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:450)
[06:44:58 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416)
[06:44:58 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142)
[06:44:58 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293)
[06:44:58 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[06:44:58 WARN]: Caused by: java.lang.NoSuchMethodException: org.mariadb.jdbc.MariaDbDataSource.<init>()
[06:44:58 WARN]:        at java.base/java.lang.Class.getConstructor0(Class.java:3517)
[06:44:58 WARN]:        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2691)
[06:44:58 WARN]:        at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:96)
[06:44:58 WARN]:        ... 21 more
```
```

**Comment by LielAmar** [comment]
Hey!
Thank you for reporting this bug. I'll fix it asap :)

**Comment by LielAmar** [comment]
Fixed in the next release (1.4.2)
