### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by LielAmar** [LielAmar/2FA#68]
**Describe the bug**
A ClassCastException

**How To Reproduce**
Run /2fa enable
No map is generated or given to the player

**Expected behavior**
No error

**Screenshots and Videos**
```
[11:48:52 WARN]: [2FA] Plugin 2FA v1.5.5 generated an exception while executing task 199
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.inventory.CraftMetaItem cannot be cast to class org.bukkit.inventory.meta.MapMeta (org.bukkit.craftbukkit.v1_17_R1.inventory.CraftMetaItem and org.bukkit.inventory.meta.MapMeta are in unnamed module of loader 'app')
        at com.lielamar.auth.bukkit.handlers.AuthHandler$3.run(AuthHandler.java:313) ~[2fa-1.5.5.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-"a740a81"]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-"a740a81"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-"a740a81"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Server Information**

**Additional context**
https://discord.com/channels/416652224505184276/606541782607724560/917019795059257354

**Comment by LielAmar** [comment]
Should be fixed. Keeping open until testing

**Comment by LielAmar** [comment]
Fixed
