### ISSUE TITLE
NoSuchMethod with MariaDB

### ISSUE THREAD

**Issue by LielAmar** [LielAmar/2FA#69]
**Describe the bug**

**How To Reproduce**

**Screenshots and Videos**
`[14:44:55 ERROR]: Error occurred while enabling 2FA v1.5.4 (Is it up to date?)
java.lang.NoSuchMethodError: 'void com.zaxxer.hikari.HikariDataSource.setKeepaliveTime(long)'
        at com.lielamar.auth.shared.storage.sql.SQLStorage.setupHikari(SQLStorage.java:60) ~[?:?]
        at com.lielamar.auth.shared.storage.sql.SQLStorage.<init>(SQLStorage.java:48) ~[?:?]
        at com.lielamar.auth.shared.storage.StorageHandler.loadStorageHandler(StorageHandler.java:123) ~[?:?]
        at com.lielamar.auth.bukkit.TwoFactorAuthentication.setupAuth(TwoFactorAuthentication.java:79) ~[?:?]
        at com.lielamar.auth.bukkit.TwoFactorAuthentication.onEnable(TwoFactorAuthentication.java:49) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[14:44:55 INFO]: [2FA] Disabling 2FA v1.5.4`

**Server Information**

**Additional context**
https://www.spigotmc.org/threads/two-factor-authentication.471366/page-5#post-4285836

**Comment by LielAmar** [comment]
Could not reproduce the error.
