### ISSUE TITLE
[Bug] After-join

### ISSUE THREAD

**Issue by msmanui** [LielAmar/2FA#82]
I have setup the 2FA in my entire network (Proxy and backend). 

Its working fine but today i switch from a server to another and for a second it will detect as i had changed my IP (In the chat will spam when trying to move). We try to replicate but we couldnt. No errors in console.

**Comment by LielAmar** [comment]
Hey!
Unfortunately that's a problem I can't fix because of the delay when syncing data across servers.
It shouldn't occur often and I'm going to add more ways to sync data in the future, so it'd be more seamless :)

**Comment by LielAmar** [comment]
Hey!
Unfortunately that's a problem I can't fix because of the delay when syncing data across servers.
It shouldn't occur often and I'm going to add more ways to sync data in the future, so it'd be more seamless :)

**Comment by msmanui** [comment]
> Unfortunately that's a problem I can't fix because of the delay when syncing data across servers.

I was using MineSecure before this 2FA and that bug never happend. 
https://www.spigotmc.org/resources/minesecure.699/

> It shouldn't occur often and I'm going to add more ways to sync data in the future, so it'd be more seamless :)

Adding redis would be really nice

**Comment by msmanui** [comment]
Is not working properly, now i've enter and:
![image](https://user-images.githubusercontent.com/63617395/160033543-a28a7b07-00cd-46f7-bae0-2e295a8d3182.png)

**Comment by msmanui** [comment]
```
[21:02:00] [Server thread/ERROR]: Something went wrong when setting up HikariCP. If something does not work correctly, please report it to the 2FA team
[21:02:00] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Starting...
[21:02:00] [Server thread/WARN]: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.mariadb.jdbc.MariaDbDataSource
[21:02:00] [Server thread/WARN]: 	at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:102)
[21:02:00] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:321)
[21:02:00] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114)
[21:02:00] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108)
[21:02:00] [Server thread/WARN]: 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
[21:02:00] [Server thread/WARN]: 	at com.lielamar.auth.shared.storage.sql.SQLStorage.createTables(SQLStorage.java:94)
[21:02:00] [Server thread/WARN]: 	at com.lielamar.auth.shared.storage.sql.SQLStorage.setupHikari(SQLStorage.java:84)
[21:02:00] [Server thread/WARN]: 	at com.lielamar.auth.shared.storage.sql.SQLStorage.<init>(SQLStorage.java:52)
[21:02:00] [Server thread/WARN]: 	at com.lielamar.auth.shared.storage.StorageHandler.loadStorageHandler(StorageHandler.java:125)
[21:02:00] [Server thread/WARN]: 	at com.lielamar.auth.bukkit.TwoFactorAuthentication.setupAuth(TwoFactorAuthentication.java:112)
[21:02:00] [Server thread/WARN]: 	at com.lielamar.auth.bukkit.TwoFactorAuthentication.onEnable(TwoFactorAuthentication.java:55)
[21:02:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:02:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[21:02:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[21:02:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472)
[21:02:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386)
[21:02:00] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
[21:02:00] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[21:02:00] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909)
[21:02:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)
[21:02:00] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.mariadb.jdbc.MariaDbDataSource
[21:02:00] [Server thread/WARN]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
[21:02:00] [Server thread/WARN]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
[21:02:00] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[21:02:00] [Server thread/WARN]: 	at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:89)
[21:02:00] [Server thread/WARN]: 	... 19 more
[21:02:00] [Server thread/ERROR]: Couldn't load the Database you specified for the above reason. Defaulting to JSON!
```

**Comment by Enoughsdv** [comment]
Hello, make sure you use the correct java version for mariadb

**Comment by msmanui** [comment]
> Hello, make sure you use the correct java version for mariadb

Im using the correct java, as no other plugin has issue with it

**Comment by Enoughsdv** [comment]
Can you send the version of MariaDB that you use? This error is rare because everything works fine on my server

**Comment by Enoughsdv** [comment]
and please send what you get by putting /2fa report

**Comment by msmanui** [comment]
This is still an issue?

**Comment by DirtyConcept** [comment]
2.0 will have a different way of handling the 2FA system, until then I'll keep the issue open, whereas 2FA service will be running either on spigot server or proxy, and will handle sessions and requests accordingly network wide.
