### ISSUE TITLE
Need 1.19 support!

### ISSUE THREAD

**Issue by moda84** [LielAmar/2FA#92]
Need 1.19 support!
[01:05:40] [Craft Scheduler Thread - 21 - 2FA/WARN]: [2FA] Plugin 2FA v1.6.2 generated an exception while executing task 2176
java.lang.NullPointerException: Cannot invoke "com.lielamar.lielsutils.bukkit.version.Version$ServerVersion.above(com.lielamar.lielsutils.bukkit.version.Version$ServerVersion)" because "this.this$0.version" is null
	at com.lielamar.auth.bukkit.handlers.AuthHandler$1.run(AuthHandler.java:204) ~[2fa-1.6.2 (2).jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1659]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.jar:git-Purpur-1659]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Enoughsdv** [comment]
Hello, can you try with the current version?

**Comment by DirtyConcept** [comment]
1.7.0 Has been released, you may download it via spigot
